### ISSUE TITLE
Missing MipNerf360 dataset files

### ISSUE THREAD

**Issue by TosakaUCW** [zju3dv/PGSR#13]
When I run the `python scripts/run_mip360.py`

It returns back:

```
rm -rf output_mip360/bicycle/test/*
CUDA_VISIBLE_DEVICES=0 python train.py -s data/MipNeRF360/bicycle -m output_mip360/bicycle/test  --eval -r4 --ncc_scale 0.5 --data_device cpu --densify_abs_grad_threshold 0.0004
Optimizing output_mip360/bicycle/test
Output folder: output_mip360/bicycle/test [25/07 16:19:11]
Tensorboard not available: not logging progress [25/07 16:19:11]
Traceback (most recent call last):
  File "/home/jovyan/work/tosaka/PGSR/scene/dataset_readers.py", line 151, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "/home/jovyan/work/tosaka/PGSR/scene/colmap_loader.py", line 197, in read_extrinsics_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/tosaka/PGSR/data/MipNeRF360/bicycle/sparse/images.bin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 495, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 97, in training
    scene = Scene(dataset, gaussians)
  File "/home/jovyan/work/tosaka/PGSR/scene/__init__.py", line 47, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/jovyan/work/tosaka/PGSR/scene/dataset_readers.py", line 156, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
  File "/home/jovyan/work/tosaka/PGSR/scene/colmap_loader.py", line 259, in read_extrinsics_text
    with open(path, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/tosaka/PGSR/data/MipNeRF360/bicycle/sparse/images.txt'
CUDA_VISIBLE_DEVICES=0 python render.py -m output_mip360/bicycle/test
Looking for config file in output_mip360/bicycle/test/cfg_args
Config file found: output_mip360/bicycle/test/cfg_args
Rendering output_mip360/bicycle/test
multi_view_num 8 [25/07 16:19:16]
Traceback (most recent call last):
  File "render.py", line 218, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.max_depth, args.voxel_size, args.use_depth_filter)
  File "render.py", line 164, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/home/jovyan/work/tosaka/PGSR/scene/__init__.py", line 38, in __init__
    self.loaded_iter = searchForMaxIteration(os.path.join(self.model_path, "point_cloud"))
  File "/home/jovyan/work/tosaka/PGSR/utils/system_utils.py", line 27, in searchForMaxIteration
    saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)]
FileNotFoundError: [Errno 2] No such file or directory: 'output_mip360/bicycle/test/point_cloud'
CUDA_VISIBLE_DEVICES=0 python metrics.py -m output_mip360/bicycle/test

Scene: output_mip360/bicycle/test
Unable to compute metrics for model output_mip360/bicycle/test
```

It seems that file missing in datasets

**Comment by danpeng2** [comment]
Hello, please ensure that the corresponding COLMAP results are here bicycle/sparse/images.bin, ... , and not in bicycle/sparse/0/images.bin, ....

**Comment by 2693748650** [comment]
> 您好，请确保对应的 COLMAP 结果在这里 bicycle/sparse/images.bin， ... ，而不是 bicycle/sparse/0/images.bin， ....

你好，我这里路径是 bicycle/sparse/0/images.bin  把dataset_readens.py里面的cameras_intrinsic_file = os.path.join(path, "sparse", "cameras.bin")变成cameras_intrinsic_file = os.path.join(path, "sparse/0", "cameras.bin")没有别的影响吧
