### ISSUE TITLE
Unable to Run train.py on NeRF Synthetic Scene

### ISSUE THREAD

**Issue by misakamage** [zju3dv/PGSR#32]
I'm encountering the following error when trying to run train.py on a NeRF Synthetic scene:
Traceback (most recent call last):
  File "train.py", line 495, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 97, in training
    scene = Scene(dataset, gaussians)
  File "/home/czy98/code_data/PGSR/scene/__init__.py", line 50, in __init__
    scene_info = sceneLoadTypeCallbacks["Blender"](args.source_path, args.white_background, args.eval)
  File "/home/czy98/code_data/PGSR/scene/dataset_readers.py", line 255, in readNerfSyntheticInfo
    train_cam_infos = readCamerasFromTransforms(path, "transforms_train.json", white_background, extension)
  File "/home/czy98/code_data/PGSR/scene/dataset_readers.py", line 248, in readCamerasFromTransforms
    cam_infos.append(CameraInfo(uid=idx, R=R, T=T, FovY=FovY, FovX=FovX, image=image,
TypeError: __new__() got an unexpected keyword argument 'image'

**Comment by renhaofan** [comment]
Have you solved this? @misakamage

**Comment by Zerui-Yu** [comment]
> Have you solved this? @misakamage 

That's just a bug. PGSR doesn't considered about nerf datasets. For the same reason the args.white_background is also invalid. I'm trying to fix it.

**Comment by Zerui-Yu** [comment]
You should modify the function in dataset_readers.py:
```
def readCamerasFromTransforms(path, transformsfile, white_background, extension=".png"):
    cam_infos = []

    with open(os.path.join(path, transformsfile)) as json_file:
        contents = json.load(json_file)
        fovx = contents["camera_angle_x"]

        frames = contents["frames"]
        for f in frames:
            f["file_path"] = f["file_path"][2:]
        for idx, frame in enumerate(frames):
            cam_name = os.path.join(path, frame["file_path"] + extension)

            # NeRF 'transform_matrix' is a camera-to-world transform
            c2w = np.array(frame["transform_matrix"])
            # change from OpenGL/Blender camera axes (Y up, Z back) to COLMAP (Y down, Z forward)
            c2w[:3, 1:3] *= -1

            # get the world-to-camera transform and set R, T
            w2c = np.linalg.inv(c2w)
            R = np.transpose(w2c[:3, :3])  # R is stored transposed due to 'glm' in CUDA code
            T = w2c[:3, 3]

            image_path = os.path.join(path, cam_name)
            image_name = Path(cam_name).stem
            image = Image.open(image_path)

            #im_data = np.array(image.convert("RGBA"))

            #bg = np.array([1, 1, 1]) if white_background else np.array([0, 0, 0])

            #norm_data = im_data / 255.0
            #arr = norm_data[:, :, :3] * norm_data[:, :, 3:4] + bg * (1 - norm_data[:, :, 3:4])
            #image = Image.fromarray(np.array(arr * 255.0, dtype=np.byte), "RGB")

            fovy = focal2fov(fov2focal(fovx, image.size[0]), image.size[1])
            FovY = fovy
            FovX = fovx
            fx = fov2focal(fovx, image.size[0])
            fy = fov2focal(fovy, image.size[1])

            cam_infos.append(CameraInfo(uid=idx, global_id=idx, R=R, T=T, FovY=FovY, FovX=FovX,
                                        image_path=image_path, image_name=image_name, width=image.size[0],
                                        height=image.size[1], fx=fx, fy=fy))

    return cam_infos
```
After that, process the background in "process_image" function of cameras.py (which was done before in readCamerasFromTransforms above, but we moved it to this function)
```
def process_image(image_path, resolution, ncc_scale, white_background=False):

    if 'nerf_synthetic' in os.path.normpath(image_path).split(os.sep):
        image = Image.open(image_path)
        im_data = np.array(image.convert("RGBA"))
        bg = np.array([1, 1, 1]) if white_background else np.array([0, 0, 0])
        norm_data = im_data / 255.0
        arr = norm_data[:, :, :3] * norm_data[:, :, 3:4] + bg * (1 - norm_data[:, :, 3:4])
        alpha = norm_data[:, :, 3:4]
        rgba = np.concatenate([arr, alpha], axis=2)
        image = Image.fromarray(np.array(rgba * 255.0, dtype=np.uint8), "RGBA")
        #image = Image.fromarray(np.array(arr * 255.0, dtype=np.byte), "RGB")
    else:
        image = Image.open(image_path)

    if len(image.split()) > 3:
        resized_image_rgb = torch.cat([PILtoTorch(im, resolution) for im in image.split()[:3]], dim=0)
        loaded_mask = PILtoTorch(image.split()[3], resolution)
        gt_image = resized_image_rgb
        if ncc_scale != 1.0:
            ncc_resolution = (int(resolution[0] / ncc_scale), int(resolution[1] / ncc_scale))
            resized_image_rgb = torch.cat([PILtoTorch(im, ncc_resolution) for im in image.split()[:3]], dim=0)
    else:
        resized_image_rgb = PILtoTorch(image, resolution)
        loaded_mask = None
        gt_image = resized_image_rgb
        if ncc_scale != 1.0:
            ncc_resolution = (int(resolution[0] / ncc_scale), int(resolution[1] / ncc_scale))
            resized_image_rgb = PILtoTorch(image, ncc_resolution)
    gray_image = (0.299 * resized_image_rgb[0] + 0.587 * resized_image_rgb[1] + 0.114 * resized_image_rgb[2])[None]

    return gt_image, gray_image, loaded_mask
```
```
class Camera(nn.Module):
    def __init__(self, colmap_id, R, T, FoVx, FoVy,
                 image_width, image_height,
                 image_path, image_name, uid,
                 trans=np.array([0.0, 0.0, 0.0]), scale=1.0,
                 ncc_scale=1.0,
                 preload_img=True, data_device="cuda", white_background=False
                 ):
        super(Camera, self).__init__()
        self.xxx = xxx (some codes)
        self.white_background = white_background
        try:
            self.data_device = torch.device(data_device)
        except Exception as e:
            print(e)
            print(f"[Warning] Custom device {data_device} failed, fallback to default cuda device")
            self.data_device = torch.device("cuda")
                self.original_image, self.image_gray, self.mask = None, None, None

        self.preload_img = preload_img
        self.ncc_scale = ncc_scale
        if self.preload_img:
            gt_image, gray_image, loaded_mask = process_image(self.image_path, self.resolution, ncc_scale, self.white_background)
            self.original_image = gt_image.to(self.data_device)
            self.original_image_gray = gray_image.to(self.data_device)
            self.mask = loaded_mask
        xxxxxx (some codes)
     def get_image(self):
        if self.preload_img:
            return self.original_image.cuda(), self.original_image_gray.cuda()
        else:
            gt_image, gray_image, _ = process_image(self.image_path, self.resolution, self.ncc_scale, self.white_background)
            return gt_image.cuda(), gray_image.cuda()
```
I hope it's helpful for you :)
Have a nice day!
