### ISSUE TITLE
RuntimeError when running custom ScanNet dataset

### ISSUE THREAD

**Issue by Planetinaline** [zju3dv/PGSR#34]
Hi and thanks for your excellent work !
I was testing a custom dataset created from scannet(simply using the 'color' folder in ScanNet scenes as the 'input' folder in custom dataset) and encountered a RuntimeError which I couldn't figure out, so i came here seeking help.
Here is the error i received when trying to run `python train.py -s /home/ubuntu/newdisk/cwk/PGSR/data/scene0003_00 -m output --max_abs_split_points 0 --opacity_cull_threshold 0.05`:
 Optimizing output
Output folder: output [08/09 20:06:31]
Tensorboard not available: not logging progress [08/09 20:06:31]
Reading camera 2/2 [08/09 20:06:31]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [08/09 20:06:31]
xyz (0, 3) [08/09 20:06:31]
cameras_extent 5.5 [08/09 20:06:31]
Loading Training Cameras [08/09 20:06:31]
load camera 1Loading Test Cameras [08/09 20:06:34]
computing nearest_id [08/09 20:06:34]
Number of points at initialisation :  0 [08/09 20:06:34]
Traceback (most recent call last):
  File "train.py", line 495, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 97, in training
    scene = Scene(dataset, gaussians)
  File "/home/ubuntu/newdisk/cwk/PGSR/scene/__init__.py", line 128, in __init__
    self.gaussians.create_from_pcd(scene_info.point_cloud, self.cameras_extent)
  File "/home/ubuntu/newdisk/cwk/PGSR/scene/gaussian_model.py", line 181, in create_from_pcd
    dist = torch.sqrt(torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001))
RuntimeError: tabulate: failed to synchronize: cudaErrorInvalidConfiguration: invalid configuration argument

**Comment by Planetinaline** [comment]
seems that it's a problem with colmap, it would crash when doing sparse reconstruction resulting in wrong points3D.ply

**Comment by 777stay** [comment]
I also encountered this issue, have you managed to resolve it?
