### ISSUE TITLE
Could not recognize scene type!

### ISSUE THREAD

**Issue by yeying256** [zju3dv/PGSR#39]
```
python train.py -s /media/a1/ubuntu_data/PGSR_data/data/ours/data/ -m /home/a1/6dpose/PGSR/ours_out/ --max_abs_split_points 0 --opacity_cull_threshold 0.05
Optimizing /home/a1/6dpose/PGSR/ours_out/
Output folder: /home/a1/6dpose/PGSR/ours_out/ [17/09 14:45:57]
Tensorboard not available: not logging progress [17/09 14:45:57]
Traceback (most recent call last):
  File "train.py", line 495, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 97, in training
    scene = Scene(dataset, gaussians)
  File "/home/a1/6dpose/PGSR/scene/__init__.py", line 52, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```
Thanks for your code.

I meet this problem when I use the custom dataset structure and run the second step 'python train.py -s data_path -m out_path --max_abs_split_points 0 --opacity_cull_threshold 0.05' .

In the first step 'python scripts/preprocess/convert.py --data_path your_data_path', I change the 'your_data_path' to '/media/a1/ubuntu_data/PGSR_data/data/ours/data'. It seems run normal. When the step 1 is over, the folder 'ours_out' appear in 'PGSR'. So I run 'python train.py -s /media/a1/ubuntu_data/PGSR_data/data/ours/data/ -m /home/a1/6dpose/PGSR/ours_out/ --max_abs_split_points 0 --opacity_cull_threshold 0.05', the error happened.

**Comment by yeying256** [comment]
OK, the error is over. The command should be " python train.py -s /media/a1/ubuntu_data/PGSR_data/data/ours/data/0410-huiyuan-box -m /home/a1/6dpose/PGSR/ours_out/0410-huiyuan-box/test --max_abs_split_points 0 --opacity_cull_threshold 0.05". The path was wrong.
